#ifndef __BOSSRUNNINGMANOBJ_H__
#define __BOSSRUNNINGMANOBJ_H__

extern u16 gBossRunningManObj_TexObjectMmTex000930Ci8;
extern u16 gBossRunningManObj_TexObjectMmTex001030Ci8;
extern u16 gBossRunningManObj_TexObjectMmTex000970Ci8;
extern u16 gBossRunningManObj_TexObjectMmTex0009F0Ci8;
extern u16 gBossRunningManObj_TexObjectMmTex000A30Ci8;
extern u16 gBossRunningManObj_TexObjectMmTex000B30Ci8;
extern u16 gBossRunningManObj_TexMouth;
extern u16 gBossRunningManObj_TexMouth0;
extern u16 gBossRunningManObj_TexMouth1;
extern u16 gBossRunningManObj_TexBnd;
extern u16 gBossRunningManObj_TexBunnyLogo;
extern Gfx gBossRunningManObj_MtlSkin;
extern Gfx gBossRunningManObj_MtlHands;
extern Gfx gBossRunningManObj_MtlHair;
extern Gfx gBossRunningManObj_MtlHairLine;
extern Gfx gBossRunningManObj_MtlEyes;
extern Gfx gBossRunningManObj_MtlEyebrows;
extern Gfx gBossRunningManObj_MtlMouth;
extern Gfx gBossRunningManObj_MtlMtl06001130;
extern Gfx gBossRunningManObj_MtlMtl06001330;
extern Gfx gBossRunningManObj_DLRunningManLimb00;
extern Gfx gBossRunningManObj_DLRunningManLimb01;
extern Gfx gBossRunningManObj_DLRunningManLimb02;
extern Gfx gBossRunningManObj_DLRunningManLimb03;
extern Gfx gBossRunningManObj_DLRunningManLimb04;
extern Gfx gBossRunningManObj_DLRunningManLimb05;
extern Gfx gBossRunningManObj_DLRunningManLimb06;
extern Gfx gBossRunningManObj_DLRunningManLimb07;
extern Gfx gBossRunningManObj_DLRunningManLimb08;
extern Gfx gBossRunningManObj_DLRunningManLimb09;
extern Gfx gBossRunningManObj_DLRunningManLimb10;
extern Gfx gBossRunningManObj_DLRunningManLimb11;
extern Gfx gBossRunningManObj_DLRunningManLimb12;
extern Gfx gBossRunningManObj_DLRunningManLimb13;
extern Gfx gBossRunningManObj_DLRunningManLimb14;
extern FlexSkeletonHeader gBossRunningManObj_SkelRunningMan;
#define  SKEL_RUNNINGMAN_NUMBONES  15
#define  SKEL_RUNNINGMAN_NUMBONES_DT  16
extern Gfx gBossRunningManObj_DLFistLLimb10;
extern Gfx gBossRunningManObj_DLFistRLimb13;
extern AnimationHeader gBossRunningManObj_AnimDeadFall;
extern AnimationHeader gBossRunningManObj_AnimDeadLoopExplain;
extern AnimationHeader gBossRunningManObj_AnimDeadLoopIdle;
extern AnimationHeader gBossRunningManObj_AnimDeadLoopRegret;
extern AnimationHeader gBossRunningManObj_AnimDodgeKick;
extern AnimationHeader gBossRunningManObj_AnimHurt;
extern AnimationHeader gBossRunningManObj_AnimJumpRocket;
extern AnimationHeader gBossRunningManObj_AnimRunFast;

#endif /* __BOSSRUNNINGMANOBJ_H__ */
