extern u64 MimicChestObj_wood_ci8[];
extern u64 MimicChestObj_wood_ci8_pal_rgba16[];
extern u64 MimicChestObj_teeth_ci8[];
extern u64 MimicChestObj_teeth_ci8_pal_rgba16[];
extern Vtx MimicChestObj_Root_mesh_layer_Opaque_vtx_0[20];
extern Gfx MimicChestObj_Root_mesh_layer_Opaque_tri_0[];
extern Vtx MimicChestObj_Root_mesh_layer_Opaque_vtx_1[4];
extern Gfx MimicChestObj_Root_mesh_layer_Opaque_tri_1[];
extern Vtx MimicChestObj_Lid_mesh_layer_Opaque_vtx_0[4];
extern Gfx MimicChestObj_Lid_mesh_layer_Opaque_tri_0[];
extern Vtx MimicChestObj_Lid_mesh_layer_Opaque_vtx_1[30];
extern Gfx MimicChestObj_Lid_mesh_layer_Opaque_tri_1[];
extern Gfx mat_MimicChestObj_Wood_layerOpaque[];
extern Gfx mat_MimicChestObj_Teeth_layerOpaque[];
extern Gfx MimicChestObj_Root_mesh_layer_Opaque[];
extern Gfx MimicChestObj_Lid_mesh_layer_Opaque[];
extern FlexSkeletonHeader MimicChestObj;
#define MIMICCHESTOBJ_ROOT_POS_LIMB 0
#define MIMICCHESTOBJ_ROOT_ROT_LIMB 1
#define MIMICCHESTOBJ_LID_LIMB 2
#define MIMICCHESTOBJ_NUM_LIMBS 3
