SUBDIRS = \
BetaGreatFairy/ \
BetaKokiri/ \
BossRunningMan/ \
BotWLink/ \
BotWZelda/ \
CoSSages/ \
CoSStaircases/ \
HolyLight/ \
Nabooru/ \
SilentPrincess/ \
TestCelShading/ \
TriforcePiece/ \
TriforceChest/ \
TriforceLight/ \
TwitchMessages/ \
WSRCutscene/ \
z_bg_mjin/ \
z_bg_spot07_taki/ \
z_bg_toki_swd/ \
z_demo_effect/ \
z_en_ge1/ \
z_en_ge2/ \
z_en_girla/ \
z_en_mm3/ \
z_en_owl/ \
z_en_skj/ \
z_en_wonder_item/ \
z_en_xc/ \
z_kaleido_scope/ \
z_oceff_wipe/ \
z_player/

.PHONY: default clean $(SUBDIRS)

default clean: $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) -C $@ $(MAKECMDGOALS)
