extern u64 gRunningManMouthClosedTex[];
extern u64 gRunningManMouthOpenTex[];
extern FlexSkeletonHeader gRunningManSkel;
extern AnimationHeader gRunningManSitWaitAnim;
extern AnimationHeader gRunningManHappyAnim;
extern AnimationHeader gRunningManExcitedAnim;
extern AnimationHeader gRunningManSitStandAnim;
extern AnimationHeader gRunningManRunAnim;
extern AnimationHeader gRunningManSprintAnim;
