extern u64 TriforceFadeWall_Beta_Triforce_Bricks_00_ci8[];
extern u64 TriforceFadeWall_Beta_Triforce_Bricks_00_ci8_pal_rgba16[];
extern Vtx TriforceFadeWall_Z_TriforceFadeWall_mesh_layer_Transparent_vtx_cull[8];
extern Vtx TriforceFadeWall_Z_TriforceFadeWall_mesh_layer_Transparent_vtx_0[20];
extern Gfx TriforceFadeWall_Z_TriforceFadeWall_mesh_layer_Transparent_tri_0[];
extern Gfx mat_TriforceFadeWall_AlphaFadeBrickWalls_layerTransparent[];
extern Gfx TriforceFadeWall[];
