extern u64 BotWLinkMesh_belt_diff_ci4[];
extern u64 BotWLinkMesh_belt_diff_ci4_pal_rgba16[];
extern u64 BotWLinkMesh_trousers_diff_ci4[];
extern u64 BotWLinkMesh_trousers_diff_ci4_pal_rgba16[];
extern u64 BotWLinkMesh_tunic_lower_diff_ci4[];
extern u64 BotWLinkMesh_tunic_lower_diff_ci4_pal_rgba16[];
extern u64 BotWLinkMesh_tunic_upper_diff_ci4[];
extern u64 BotWLinkMesh_tunic_upper_diff_ci4_pal_rgba16[];
extern u64 BotWLinkMesh_boots_diff_ci4[];
extern u64 BotWLinkMesh_boots_diff_ci4_pal_rgba16[];
extern u64 BotWLinkMesh_head_diff_ci4[];
extern u64 BotWLinkMesh_head_diff_ci4_pal_rgba16[];
extern u64 BotWLinkMesh_undershirt_diff_ci4[];
extern u64 BotWLinkMesh_undershirt_diff_ci4_pal_rgba16[];
extern u64 BotWLinkMesh_tunic_sleeves_diff_ci4[];
extern u64 BotWLinkMesh_tunic_sleeves_diff_ci4_pal_rgba16[];
extern u64 BotWLinkMesh_skin_diff_ci4[];
extern u64 BotWLinkMesh_skin_diff_ci4_pal_rgba16[];
extern u64 BotWLinkMesh_gloves_diff_ci4[];
extern u64 BotWLinkMesh_gloves_diff_ci4_pal_rgba16[];
extern u64 BotWLinkMesh_armcover_diff_ci4[];
extern u64 BotWLinkMesh_armcover_diff_ci4_pal_rgba16[];
extern u64 BotWLinkMesh_gauntlet_diff_ci4[];
extern u64 BotWLinkMesh_gauntlet_diff_ci4_pal_rgba16[];
extern Vtx BotWLinkMesh_Hips_mesh_layer_Opaque_vtx_0[94];
extern Gfx BotWLinkMesh_Hips_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_Hips_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWLinkMesh_Hips_mesh_layer_Opaque_tri_0_cel2[];
extern Gfx BotWLinkMesh_Hips_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_Hips_mesh_layer_Opaque_vtx_1[16];
extern Gfx BotWLinkMesh_Hips_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWLinkMesh_Hips_mesh_layer_Opaque_tri_1[];
extern Vtx BotWLinkMesh_Hips_mesh_layer_Opaque_vtx_2[28];
extern Gfx BotWLinkMesh_Hips_mesh_layer_Opaque_tri_2_cel0[];
extern Gfx BotWLinkMesh_Hips_mesh_layer_Opaque_tri_2[];
extern Vtx BotWLinkMesh_Hips_mesh_layer_Opaque_vtx_3[24];
extern Gfx BotWLinkMesh_Hips_mesh_layer_Opaque_tri_3_cel0[];
extern Gfx BotWLinkMesh_Hips_mesh_layer_Opaque_tri_3[];
extern Vtx BotWLinkMesh_LoTncBL_mesh_layer_Opaque_vtx_0[11];
extern Gfx BotWLinkMesh_LoTncBL_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_LoTncBL_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_LoTncBR_mesh_layer_Opaque_vtx_0[11];
extern Gfx BotWLinkMesh_LoTncBR_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_LoTncBR_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_LoTncFC_mesh_layer_Opaque_vtx_0[8];
extern Gfx BotWLinkMesh_LoTncFC_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_LoTncFC_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_LoTncFL_mesh_layer_Opaque_vtx_0[9];
extern Gfx BotWLinkMesh_LoTncFL_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_LoTncFL_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_LoTncFR_mesh_layer_Opaque_vtx_0[9];
extern Gfx BotWLinkMesh_LoTncFR_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_LoTncFR_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_LThigh_mesh_layer_Opaque_vtx_0[30];
extern Gfx BotWLinkMesh_LThigh_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_LThigh_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_LCalf_mesh_layer_Opaque_vtx_0[18];
extern Gfx BotWLinkMesh_LCalf_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_LCalf_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_LCalf_mesh_layer_Opaque_vtx_1[88];
extern Gfx BotWLinkMesh_LCalf_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWLinkMesh_LCalf_mesh_layer_Opaque_tri_1_cel1[];
extern Gfx BotWLinkMesh_LCalf_mesh_layer_Opaque_tri_1_cel2[];
extern Gfx BotWLinkMesh_LCalf_mesh_layer_Opaque_tri_1[];
extern Vtx BotWLinkMesh_LFoot_mesh_layer_Opaque_vtx_0[71];
extern Gfx BotWLinkMesh_LFoot_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_LFoot_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWLinkMesh_LFoot_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_RThigh_mesh_layer_Opaque_vtx_0[30];
extern Gfx BotWLinkMesh_RThigh_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_RThigh_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_RCalf_mesh_layer_Opaque_vtx_0[18];
extern Gfx BotWLinkMesh_RCalf_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_RCalf_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_RCalf_mesh_layer_Opaque_vtx_1[89];
extern Gfx BotWLinkMesh_RCalf_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWLinkMesh_RCalf_mesh_layer_Opaque_tri_1_cel1[];
extern Gfx BotWLinkMesh_RCalf_mesh_layer_Opaque_tri_1_cel2[];
extern Gfx BotWLinkMesh_RCalf_mesh_layer_Opaque_tri_1[];
extern Vtx BotWLinkMesh_RFoot_mesh_layer_Opaque_vtx_0[64];
extern Gfx BotWLinkMesh_RFoot_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_RFoot_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWLinkMesh_RFoot_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_Torso_mesh_layer_Opaque_vtx_0[27];
extern Gfx BotWLinkMesh_Torso_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_Torso_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_Torso_mesh_layer_Opaque_vtx_1[7];
extern Gfx BotWLinkMesh_Torso_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWLinkMesh_Torso_mesh_layer_Opaque_tri_1[];
extern Vtx BotWLinkMesh_Torso_mesh_layer_Opaque_vtx_2[153];
extern Gfx BotWLinkMesh_Torso_mesh_layer_Opaque_tri_2_cel0[];
extern Gfx BotWLinkMesh_Torso_mesh_layer_Opaque_tri_2_cel1[];
extern Gfx BotWLinkMesh_Torso_mesh_layer_Opaque_tri_2_cel2[];
extern Gfx BotWLinkMesh_Torso_mesh_layer_Opaque_tri_2_cel3[];
extern Gfx BotWLinkMesh_Torso_mesh_layer_Opaque_tri_2_cel4[];
extern Gfx BotWLinkMesh_Torso_mesh_layer_Opaque_tri_2[];
extern Vtx BotWLinkMesh_Head_mesh_layer_Opaque_vtx_0[167];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_0_cel2[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_0_cel3[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_0_cel4[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_Head_mesh_layer_Opaque_vtx_1[16];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_1[];
extern Vtx BotWLinkMesh_Head_mesh_layer_Opaque_vtx_2[202];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_2_cel0[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_2_cel1[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_2_cel2[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_2_cel3[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_2_cel4[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_2_cel5[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_2_cel6[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_2[];
extern Vtx BotWLinkMesh_Head_mesh_layer_Opaque_vtx_3[12];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_3_cel0[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque_tri_3[];
extern Vtx BotWLinkMesh_Bangs1_mesh_layer_Opaque_vtx_0[20];
extern Gfx BotWLinkMesh_Bangs1_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_Bangs1_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_Bangs2_mesh_layer_Opaque_vtx_0[9];
extern Gfx BotWLinkMesh_Bangs2_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_Bangs2_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_Bangs3_mesh_layer_Opaque_vtx_0[16];
extern Gfx BotWLinkMesh_Bangs3_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_Bangs3_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_Jaw_mesh_layer_Opaque_vtx_0[81];
extern Gfx BotWLinkMesh_Jaw_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_Jaw_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWLinkMesh_Jaw_mesh_layer_Opaque_tri_0_cel2[];
extern Gfx BotWLinkMesh_Jaw_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_LMouth_mesh_layer_Opaque_vtx_0[18];
extern Gfx BotWLinkMesh_LMouth_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_LMouth_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_LTassels_mesh_layer_Opaque_vtx_0[35];
extern Gfx BotWLinkMesh_LTassels_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_LTassels_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_Ponytail_mesh_layer_Opaque_vtx_0[70];
extern Gfx BotWLinkMesh_Ponytail_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_Ponytail_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWLinkMesh_Ponytail_mesh_layer_Opaque_tri_0_cel2[];
extern Gfx BotWLinkMesh_Ponytail_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_RMouth_mesh_layer_Opaque_vtx_0[18];
extern Gfx BotWLinkMesh_RMouth_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_RMouth_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_RTassels_mesh_layer_Opaque_vtx_0[37];
extern Gfx BotWLinkMesh_RTassels_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_RTassels_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_LUpArm_mesh_layer_Opaque_vtx_0[26];
extern Gfx BotWLinkMesh_LUpArm_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_LUpArm_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_LUpArm_mesh_layer_Opaque_vtx_1[16];
extern Gfx BotWLinkMesh_LUpArm_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWLinkMesh_LUpArm_mesh_layer_Opaque_tri_1[];
extern Vtx BotWLinkMesh_LLoArm_mesh_layer_Opaque_vtx_0[16];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_LLoArm_mesh_layer_Opaque_vtx_1[95];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_1_cel1[];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_1_cel2[];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_1[];
extern Vtx BotWLinkMesh_LLoArm_mesh_layer_Opaque_vtx_2[93];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_2_cel0[];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_2_cel1[];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_2_cel2[];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_2[];
extern Vtx BotWLinkMesh_LLoArm_mesh_layer_Opaque_vtx_3[53];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_3_cel0[];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_3_cel1[];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque_tri_3[];
extern Vtx BotWLinkMesh_RUpArm_mesh_layer_Opaque_vtx_0[26];
extern Gfx BotWLinkMesh_RUpArm_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_RUpArm_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_RUpArm_mesh_layer_Opaque_vtx_1[16];
extern Gfx BotWLinkMesh_RUpArm_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWLinkMesh_RUpArm_mesh_layer_Opaque_tri_1[];
extern Vtx BotWLinkMesh_RLoArm_mesh_layer_Opaque_vtx_0[16];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_0[];
extern Vtx BotWLinkMesh_RLoArm_mesh_layer_Opaque_vtx_1[95];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_1_cel1[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_1_cel2[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_1[];
extern Vtx BotWLinkMesh_RLoArm_mesh_layer_Opaque_vtx_2[100];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_2_cel0[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_2_cel1[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_2_cel2[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_2[];
extern Vtx BotWLinkMesh_RLoArm_mesh_layer_Opaque_vtx_3[132];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_3_cel0[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_3_cel1[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_3_cel2[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_3_cel3[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_3[];
extern Vtx BotWLinkMesh_RLoArm_mesh_layer_Opaque_vtx_4[52];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_4_cel0[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_4_cel1[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque_tri_4[];
extern Gfx mat_BotWLinkMesh_N_Belt_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Trousers_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Tunic_Lower_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Tunic_Upper_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Boots_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Face_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Undershirts_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Eyes_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Hair_Complex_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Hairband_Solid_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Hair_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Tunic_Sleeves_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Undershirt_Solid_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Skin_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Gloves_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Arm_Cover_layerOpaque[];
extern Gfx mat_BotWLinkMesh_N_Gauntlet_layerOpaque[];
extern Gfx BotWLinkMesh_Hips_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LoTncBC_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LoTncBL_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LoTncBR_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LoTncFC_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LoTncFL_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LoTncFR_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LThigh_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LCalf_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LFoot_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_RThigh_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_RCalf_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_RFoot_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_Torso_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_Head_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_Bangs1_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_Bangs2_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_Bangs3_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_Jaw_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LMouth_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LTassels_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_Ponytail_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_RMouth_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_RTassels_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LUpArm_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_LLoArm_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_RUpArm_mesh_layer_Opaque[];
extern Gfx BotWLinkMesh_RLoArm_mesh_layer_Opaque[];
extern FlexSkeletonHeader BotWLinkMesh;
#define BOTWLINKMESH_ROOT_POS_LIMB 0
#define BOTWLINKMESH_ROOT_ROT_LIMB 1
#define BOTWLINKMESH_HIPS_LIMB 2
#define BOTWLINKMESH_LOTNCBC_LIMB 3
#define BOTWLINKMESH_LOTNCBL_LIMB 4
#define BOTWLINKMESH_LOTNCBR_LIMB 5
#define BOTWLINKMESH_LOTNCFC_LIMB 6
#define BOTWLINKMESH_LOTNCFL_LIMB 7
#define BOTWLINKMESH_LOTNCFR_LIMB 8
#define BOTWLINKMESH_LTHIGH_LIMB 9
#define BOTWLINKMESH_LCALF_LIMB 10
#define BOTWLINKMESH_LFOOT_LIMB 11
#define BOTWLINKMESH_RTHIGH_LIMB 12
#define BOTWLINKMESH_RCALF_LIMB 13
#define BOTWLINKMESH_RFOOT_LIMB 14
#define BOTWLINKMESH_TORSO_LIMB 15
#define BOTWLINKMESH_HEAD_LIMB 16
#define BOTWLINKMESH_BANGS1_LIMB 17
#define BOTWLINKMESH_BANGS2_LIMB 18
#define BOTWLINKMESH_BANGS3_LIMB 19
#define BOTWLINKMESH_JAW_LIMB 20
#define BOTWLINKMESH_LMOUTH_LIMB 21
#define BOTWLINKMESH_LTASSELS_LIMB 22
#define BOTWLINKMESH_PONYTAIL_LIMB 23
#define BOTWLINKMESH_RMOUTH_LIMB 24
#define BOTWLINKMESH_RTASSELS_LIMB 25
#define BOTWLINKMESH_LUPARM_LIMB 26
#define BOTWLINKMESH_LLOARM_LIMB 27
#define BOTWLINKMESH_RUPARM_LIMB 28
#define BOTWLINKMESH_RLOARM_LIMB 29
#define BOTWLINKMESH_NUM_LIMBS 30
