extern u64 PatrickStarObj_trousers_ci4[];
extern u64 PatrickStarObj_trousers_ci4_pal_rgba16[];
extern u64 PatrickStarObj_eyes_ia4[];
extern Vtx PatrickStarObj_Root_mesh_layer_Opaque_vtx_0[18];
extern Gfx PatrickStarObj_Root_mesh_layer_Opaque_tri_0[];
extern Vtx PatrickStarObj_Root_mesh_layer_Opaque_vtx_1[15];
extern Gfx PatrickStarObj_Root_mesh_layer_Opaque_tri_1[];
extern Vtx PatrickStarObj_Torso_mesh_layer_Opaque_vtx_0[28];
extern Gfx PatrickStarObj_Torso_mesh_layer_Opaque_tri_0[];
extern Vtx PatrickStarObj_Head_mesh_layer_Opaque_vtx_0[48];
extern Gfx PatrickStarObj_Head_mesh_layer_Opaque_tri_0[];
extern Vtx PatrickStarObj_Head_mesh_layer_Opaque_vtx_1[12];
extern Gfx PatrickStarObj_Head_mesh_layer_Opaque_tri_1[];
extern Vtx PatrickStarObj_Head_mesh_layer_Opaque_vtx_2[6];
extern Gfx PatrickStarObj_Head_mesh_layer_Opaque_tri_2[];
extern Vtx PatrickStarObj_LArm_mesh_layer_Opaque_vtx_0[6];
extern Gfx PatrickStarObj_LArm_mesh_layer_Opaque_tri_0[];
extern Vtx PatrickStarObj_LHand_mesh_layer_Opaque_vtx_0[6];
extern Gfx PatrickStarObj_LHand_mesh_layer_Opaque_tri_0[];
extern Vtx PatrickStarObj_RArm_mesh_layer_Opaque_vtx_0[6];
extern Gfx PatrickStarObj_RArm_mesh_layer_Opaque_tri_0[];
extern Vtx PatrickStarObj_RHand_mesh_layer_Opaque_vtx_0[6];
extern Gfx PatrickStarObj_RHand_mesh_layer_Opaque_tri_0[];
extern Gfx mat_PatrickStarObj_Trousers_layerOpaque[];
extern Gfx mat_PatrickStarObj_PinkBody_layerOpaque[];
extern Gfx mat_PatrickStarObj_Mouth_layerOpaque[];
extern Gfx mat_PatrickStarObj_Eyes_layerOpaque[];
extern Gfx PatrickStarObj_Root_mesh_layer_Opaque[];
extern Gfx PatrickStarObj_Torso_mesh_layer_Opaque[];
extern Gfx PatrickStarObj_Head_mesh_layer_Opaque[];
extern Gfx PatrickStarObj_LArm_mesh_layer_Opaque[];
extern Gfx PatrickStarObj_LHand_mesh_layer_Opaque[];
extern Gfx PatrickStarObj_RArm_mesh_layer_Opaque[];
extern Gfx PatrickStarObj_RHand_mesh_layer_Opaque[];
extern FlexSkeletonHeader PatrickStarObj;
#define PATRICKSTAROBJ_ROOT_POS_LIMB 0
#define PATRICKSTAROBJ_ROOT_ROT_LIMB 1
#define PATRICKSTAROBJ_TORSO_LIMB 2
#define PATRICKSTAROBJ_HEAD_LIMB 3
#define PATRICKSTAROBJ_LARM_LIMB 4
#define PATRICKSTAROBJ_LHAND_LIMB 5
#define PATRICKSTAROBJ_RARM_LIMB 6
#define PATRICKSTAROBJ_RHAND_LIMB 7
#define PATRICKSTAROBJ_NUM_LIMBS 8
