include ../../toolchain/make/main.mk

ACTORNAME = ovl_player_actor
ACTORDIR = ../../build-romhack/system/overlay/ovl_player_actor
ORIGMD5 = 58b2c8810636b93f805d55182144236a
EXTRALDS = ../../statics/statics.out.ld

include ../../toolchain/make/actorpatch.mk
