extern u64 BotWZeldaMesh_body_ci4[];
extern u64 BotWZeldaMesh_body_ci4_pal_rgba16[];
extern u64 BotWZeldaMesh_dress_ci4[];
extern u64 BotWZeldaMesh_dress_ci4_pal_rgba16[];
extern u64 BotWZeldaMesh_dress_pleats_ci4[];
extern u64 BotWZeldaMesh_dress_pleats_ci4_pal_rgba16[];
extern u64 BotWZeldaMesh_belt_ci4[];
extern u64 BotWZeldaMesh_belt_ci4_pal_rgba16[];
extern u64 BotWZeldaMesh_buckle2_ci4[];
extern u64 BotWZeldaMesh_buckle2_ci4_pal_rgba16[];
extern u64 BotWZeldaMesh_head_ci4[];
extern u64 BotWZeldaMesh_head_ci4_pal_rgba16[];
extern u64 BotWZeldaMesh_bracelet_ci4[];
extern u64 BotWZeldaMesh_bracelet_ci4_pal_rgba16[];
extern Vtx BotWZeldaMesh_Root_mesh_layer_Opaque_vtx_0[210];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque_tri_0_cel2[];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque_tri_0_cel3[];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque_tri_0_cel4[];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque_tri_0_cel5[];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque_tri_0_cel6[];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_Root_mesh_layer_Opaque_vtx_1[79];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque_tri_1_cel1[];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque_tri_1_cel2[];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque_tri_1[];
extern Vtx BotWZeldaMesh_DressF_mesh_layer_Opaque_vtx_0[20];
extern Gfx BotWZeldaMesh_DressF_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_DressF_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_DressF_mesh_layer_Opaque_vtx_1[12];
extern Gfx BotWZeldaMesh_DressF_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWZeldaMesh_DressF_mesh_layer_Opaque_tri_1[];
extern Vtx BotWZeldaMesh_DressL_mesh_layer_Opaque_vtx_0[77];
extern Gfx BotWZeldaMesh_DressL_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_DressL_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWZeldaMesh_DressL_mesh_layer_Opaque_tri_0_cel2[];
extern Gfx BotWZeldaMesh_DressL_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_DressR_mesh_layer_Opaque_vtx_0[76];
extern Gfx BotWZeldaMesh_DressR_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_DressR_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWZeldaMesh_DressR_mesh_layer_Opaque_tri_0_cel2[];
extern Gfx BotWZeldaMesh_DressR_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_Torso_mesh_layer_Opaque_vtx_0[102];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_0_cel2[];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_0_cel3[];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_Torso_mesh_layer_Opaque_vtx_1[19];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_1[];
extern Vtx BotWZeldaMesh_Torso_mesh_layer_Opaque_vtx_2[95];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_2_cel0[];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_2_cel1[];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_2_cel2[];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_2[];
extern Vtx BotWZeldaMesh_Torso_mesh_layer_Opaque_vtx_3[19];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_3_cel0[];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_3[];
extern Vtx BotWZeldaMesh_Torso_mesh_layer_Opaque_vtx_4[16];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_4_cel0[];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque_tri_4[];
extern Vtx BotWZeldaMesh_Head_mesh_layer_Opaque_vtx_0[151];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_0_cel2[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_0_cel3[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_0_cel4[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_Head_mesh_layer_Opaque_vtx_1[10];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_1[];
extern Vtx BotWZeldaMesh_Head_mesh_layer_Opaque_vtx_2[16];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_2_cel0[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_2[];
extern Vtx BotWZeldaMesh_Head_mesh_layer_Opaque_vtx_3[195];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_3_cel0[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_3_cel1[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_3_cel2[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_3_cel3[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_3_cel4[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_3_cel5[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque_tri_3[];
extern Vtx BotWZeldaMesh_HairC_mesh_layer_Opaque_vtx_0[32];
extern Gfx BotWZeldaMesh_HairC_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_HairC_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_HairL_mesh_layer_Opaque_vtx_0[30];
extern Gfx BotWZeldaMesh_HairL_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_HairL_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_HairR_mesh_layer_Opaque_vtx_0[30];
extern Gfx BotWZeldaMesh_HairR_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_HairR_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_Jaw_mesh_layer_Opaque_vtx_0[60];
extern Gfx BotWZeldaMesh_Jaw_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_Jaw_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWZeldaMesh_Jaw_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_Jaw_mesh_layer_Opaque_vtx_1[14];
extern Gfx BotWZeldaMesh_Jaw_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWZeldaMesh_Jaw_mesh_layer_Opaque_tri_1[];
extern Vtx BotWZeldaMesh_MouthL_mesh_layer_Opaque_vtx_0[15];
extern Gfx BotWZeldaMesh_MouthL_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_MouthL_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_MouthR_mesh_layer_Opaque_vtx_0[15];
extern Gfx BotWZeldaMesh_MouthR_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_MouthR_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_MouthU_mesh_layer_Opaque_vtx_0[19];
extern Gfx BotWZeldaMesh_MouthU_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_MouthU_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_LUpArm_mesh_layer_Opaque_vtx_0[52];
extern Gfx BotWZeldaMesh_LUpArm_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_LUpArm_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWZeldaMesh_LUpArm_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_LLoArm_mesh_layer_Opaque_vtx_0[27];
extern Gfx BotWZeldaMesh_LLoArm_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_LLoArm_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_LLoArm_mesh_layer_Opaque_vtx_1[18];
extern Gfx BotWZeldaMesh_LLoArm_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWZeldaMesh_LLoArm_mesh_layer_Opaque_tri_1[];
extern Vtx BotWZeldaMesh_LHand_mesh_layer_Opaque_vtx_0[105];
extern Gfx BotWZeldaMesh_LHand_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_LHand_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWZeldaMesh_LHand_mesh_layer_Opaque_tri_0_cel2[];
extern Gfx BotWZeldaMesh_LHand_mesh_layer_Opaque_tri_0_cel3[];
extern Gfx BotWZeldaMesh_LHand_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_RUpArm_mesh_layer_Opaque_vtx_0[52];
extern Gfx BotWZeldaMesh_RUpArm_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_RUpArm_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWZeldaMesh_RUpArm_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_RLoArm_mesh_layer_Opaque_vtx_0[27];
extern Gfx BotWZeldaMesh_RLoArm_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_RLoArm_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_RLoArm_mesh_layer_Opaque_vtx_1[18];
extern Gfx BotWZeldaMesh_RLoArm_mesh_layer_Opaque_tri_1_cel0[];
extern Gfx BotWZeldaMesh_RLoArm_mesh_layer_Opaque_tri_1[];
extern Vtx BotWZeldaMesh_RHand_mesh_layer_Opaque_vtx_0[57];
extern Gfx BotWZeldaMesh_RHand_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_RHand_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWZeldaMesh_RHand_mesh_layer_Opaque_tri_0[];
extern Vtx BotWZeldaMesh_RFingers_mesh_layer_Opaque_vtx_0[55];
extern Gfx BotWZeldaMesh_RFingers_mesh_layer_Opaque_tri_0_cel0[];
extern Gfx BotWZeldaMesh_RFingers_mesh_layer_Opaque_tri_0_cel1[];
extern Gfx BotWZeldaMesh_RFingers_mesh_layer_Opaque_tri_0[];
extern Gfx mat_BotWZeldaMesh_N_Body_layerOpaque[];
extern Gfx mat_BotWZeldaMesh_N_Dress_layerOpaque[];
extern Gfx mat_BotWZeldaMesh_N_Dress_Pleats_layerOpaque[];
extern Gfx mat_BotWZeldaMesh_N_Belt_layerOpaque[];
extern Gfx mat_BotWZeldaMesh_N_Buckle_2_layerOpaque[];
extern Gfx mat_BotWZeldaMesh_N_Head_layerOpaque[];
extern Gfx mat_BotWZeldaMesh_N_Eyes_layerOpaque[];
extern Gfx mat_BotWZeldaMesh_N_Hair_1s_layerOpaque[];
extern Gfx mat_BotWZeldaMesh_N_Bracelet_layerOpaque[];
extern Gfx BotWZeldaMesh_Root_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_DressB_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_DressF_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_DressL_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_DressR_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_Torso_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_Head_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_HairC_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_HairL_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_HairR_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_Jaw_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_MouthL_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_MouthR_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_MouthU_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_LUpArm_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_LLoArm_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_LHand_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_RUpArm_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_RLoArm_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_RHand_mesh_layer_Opaque[];
extern Gfx BotWZeldaMesh_RFingers_mesh_layer_Opaque[];
extern FlexSkeletonHeader BotWZeldaMesh;
#define BOTWZELDAMESH_ROOT_POS_LIMB 0
#define BOTWZELDAMESH_ROOT_ROT_LIMB 1
#define BOTWZELDAMESH_DRESSB_LIMB 2
#define BOTWZELDAMESH_DRESSF_LIMB 3
#define BOTWZELDAMESH_DRESSL_LIMB 4
#define BOTWZELDAMESH_DRESSR_LIMB 5
#define BOTWZELDAMESH_TORSO_LIMB 6
#define BOTWZELDAMESH_HEAD_LIMB 7
#define BOTWZELDAMESH_HAIRC_LIMB 8
#define BOTWZELDAMESH_HAIRL_LIMB 9
#define BOTWZELDAMESH_HAIRR_LIMB 10
#define BOTWZELDAMESH_JAW_LIMB 11
#define BOTWZELDAMESH_MOUTHL_LIMB 12
#define BOTWZELDAMESH_MOUTHR_LIMB 13
#define BOTWZELDAMESH_MOUTHU_LIMB 14
#define BOTWZELDAMESH_LUPARM_LIMB 15
#define BOTWZELDAMESH_LLOARM_LIMB 16
#define BOTWZELDAMESH_LHAND_LIMB 17
#define BOTWZELDAMESH_RUPARM_LIMB 18
#define BOTWZELDAMESH_RLOARM_LIMB 19
#define BOTWZELDAMESH_RHAND_LIMB 20
#define BOTWZELDAMESH_RFINGERS_LIMB 21
#define BOTWZELDAMESH_NUM_LIMBS 22
