include ../../toolchain/make/main.mk

ACTORNAME = ovl_kaleido_scope
ACTORDIR = ../../build-romhack/system/overlay/ovl_kaleido_scope
ORIGMD5 = c59ed87e28ec60a23d8f9106ff671a3e
EXTRALDS = ../../statics/statics.out.ld

include ../../toolchain/make/actorpatch.mk
